
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

 /*
 * Program Name: GB MFG Inventory Management System
 * Programmer's Name: Alfred Beam
 * Program Description: A GUI program that manages tool and material inventory.           
 *                      
 */
public class MainMenu extends javax.swing.JFrame
{

    /**
     * Creates new form WorkOrder
     */
    public MainMenu()
    {
        initComponents();

        // center the Work Order form
        this.setLocationRelativeTo(null);

        // set the Work Order background color
        //this.getContentPane().setBackground(Color.LIGHT_GRAY);
        //this.getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        mnuMain = new javax.swing.JTabbedPane();
        pnlMain = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton();
        lblUserID = new javax.swing.JLabel();
        txtUserID = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        btnLogout = new javax.swing.JButton();
        pnlWorkOrder = new javax.swing.JPanel();
        lblWorkOrder = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblStreet1 = new javax.swing.JLabel();
        txtWorkOrderNumber = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        lblDate = new javax.swing.JLabel();
        lblCompanyName = new javax.swing.JLabel();
        lblStreet = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        pnlTools = new javax.swing.JPanel();
        btnDisplayToolList = new javax.swing.JButton();
        btnAddTool = new javax.swing.JButton();
        txtToolName = new javax.swing.JTextField();
        lblToolName = new javax.swing.JLabel();
        txtToolSerialNumber = new javax.swing.JTextField();
        lblToolSerialNumber = new javax.swing.JLabel();
        txtToolValue = new javax.swing.JTextField();
        lblToolValue = new javax.swing.JLabel();
        scrToolTable = new javax.swing.JScrollPane();
        tblToolTable = new javax.swing.JTable();
        lblToolID = new javax.swing.JLabel();
        txtToolID = new javax.swing.JTextField();
        btnDeleteToo1 = new javax.swing.JButton();
        pnlMaterials = new javax.swing.JPanel();
        btnLoadMaterialList = new javax.swing.JButton();
        mnbMain = new javax.swing.JMenuBar();
        mnuFile = new javax.swing.JMenu();
        mniNewWorkOrder = new javax.swing.JMenuItem();
        mniOpen = new javax.swing.JMenuItem();
        mniExit = new javax.swing.JMenuItem();
        mnuEdit = new javax.swing.JMenu();
        mniClear = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GB Manufacturing Inventory Management System");

        btnLogin.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblUserID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblUserID.setText("User ID:");

        txtUserID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserIDActionPerformed(evt);
            }
        });

        lblPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPassword.setText("Password:");

        txtPassword.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        btnLogout.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addComponent(lblPassword)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMainLayout.createSequentialGroup()
                            .addComponent(lblUserID)
                            .addGap(18, 18, 18)
                            .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addComponent(btnLogin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogout)))
                .addContainerGap(512, Short.MAX_VALUE))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPassword))
                .addGap(18, 18, 18)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(btnLogout))
                .addContainerGap(568, Short.MAX_VALUE))
        );

        mnuMain.addTab("Main Menu", pnlMain);

        lblWorkOrder.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lblWorkOrder.setForeground(new java.awt.Color(0, 0, 255));
        lblWorkOrder.setText("WORK ORDER");

        lblPhone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblPhone.setText("Phone: 1-800-555-1212");

        lblStreet1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblStreet1.setText("Work Order #:");

        txtWorkOrderNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        txtDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblDate.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblDate.setText("Date:");

        lblCompanyName.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        lblCompanyName.setText("GB Manufacturing");

        lblStreet.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblStreet.setText("135 Liberty Ave.");

        lblCity.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblCity.setText("Brooklyn, NY 11212");

        javax.swing.GroupLayout pnlWorkOrderLayout = new javax.swing.GroupLayout(pnlWorkOrder);
        pnlWorkOrder.setLayout(pnlWorkOrderLayout);
        pnlWorkOrderLayout.setHorizontalGroup(
            pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCompanyName)
                    .addComponent(lblStreet)
                    .addComponent(lblCity)
                    .addComponent(lblPhone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 355, Short.MAX_VALUE)
                .addGroup(pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblWorkOrder, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkOrderLayout.createSequentialGroup()
                        .addComponent(lblStreet1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWorkOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlWorkOrderLayout.createSequentialGroup()
                        .addComponent(lblDate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlWorkOrderLayout.setVerticalGroup(
            pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlWorkOrderLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlWorkOrderLayout.createSequentialGroup()
                        .addComponent(lblCompanyName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblStreet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPhone))
                    .addGroup(pnlWorkOrderLayout.createSequentialGroup()
                        .addComponent(lblWorkOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWorkOrderNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStreet1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlWorkOrderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblDate))))
                .addContainerGap(581, Short.MAX_VALUE))
        );

        mnuMain.addTab("Work Order", pnlWorkOrder);

        btnDisplayToolList.setText("Display Tools");
        btnDisplayToolList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDisplayToolListActionPerformed(evt);
            }
        });

        btnAddTool.setText("Add Tool");
        btnAddTool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToolActionPerformed(evt);
            }
        });

        txtToolName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtToolName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToolNameActionPerformed(evt);
            }
        });

        lblToolName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblToolName.setText("Tool Name:");

        txtToolSerialNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblToolSerialNumber.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblToolSerialNumber.setText("Tool Serial Number:");

        txtToolValue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lblToolValue.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblToolValue.setText("Tool Value:");

        tblToolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrToolTable.setViewportView(tblToolTable);

        lblToolID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblToolID.setText("Tool ID:");

        txtToolID.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        txtToolID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtToolIDActionPerformed(evt);
            }
        });

        btnDeleteToo1.setText("Delete Tool");
        btnDeleteToo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteToo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlToolsLayout = new javax.swing.GroupLayout(pnlTools);
        pnlTools.setLayout(pnlToolsLayout);
        pnlToolsLayout.setHorizontalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrToolTable)
                    .addGroup(pnlToolsLayout.createSequentialGroup()
                        .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addComponent(lblToolName)
                                .addGap(46, 46, 46)
                                .addComponent(txtToolName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblToolSerialNumber)
                                    .addComponent(lblToolValue))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtToolValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtToolSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addComponent(btnAddTool, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnDisplayToolList)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, Short.MAX_VALUE)
                        .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlToolsLayout.createSequentialGroup()
                                .addComponent(lblToolID)
                                .addGap(46, 46, 46)
                                .addComponent(txtToolID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDeleteToo1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnlToolsLayout.setVerticalGroup(
            pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblToolID)
                        .addComponent(txtToolID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblToolName)
                        .addComponent(txtToolName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToolSerialNumber)
                    .addComponent(txtToolSerialNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToolValue)
                    .addComponent(txtToolValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddTool)
                    .addComponent(btnDisplayToolList)
                    .addComponent(btnDeleteToo1))
                .addGap(18, 18, 18)
                .addComponent(scrToolTable, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE))
        );

        mnuMain.addTab("Tools", pnlTools);

        btnLoadMaterialList.setText("Load Materials");
        btnLoadMaterialList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadMaterialListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMaterialsLayout = new javax.swing.GroupLayout(pnlMaterials);
        pnlMaterials.setLayout(pnlMaterialsLayout);
        pnlMaterialsLayout.setHorizontalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoadMaterialList)
                .addContainerGap(565, Short.MAX_VALUE))
        );
        pnlMaterialsLayout.setVerticalGroup(
            pnlMaterialsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMaterialsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLoadMaterialList)
                .addContainerGap(642, Short.MAX_VALUE))
        );

        mnuMain.addTab("Materials", pnlMaterials);

        mnuFile.setText("File");

        mniNewWorkOrder.setText("New");
        mniNewWorkOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniNewWorkOrderActionPerformed(evt);
            }
        });
        mnuFile.add(mniNewWorkOrder);

        mniOpen.setText("Open");
        mniOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniOpenActionPerformed(evt);
            }
        });
        mnuFile.add(mniOpen);

        mniExit.setText("Exit");
        mniExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniExitActionPerformed(evt);
            }
        });
        mnuFile.add(mniExit);

        mnbMain.add(mnuFile);

        mnuEdit.setText("Edit");

        mniClear.setText("Clear");
        mniClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniClearActionPerformed(evt);
            }
        });
        mnuEdit.add(mniClear);

        mnbMain.add(mnuEdit);

        setJMenuBar(mnbMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mnuMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mniExitActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniExitActionPerformed
    {//GEN-HEADEREND:event_mniExitActionPerformed
        // exit the application
        System.exit(0);
    }//GEN-LAST:event_mniExitActionPerformed

    private void mniNewWorkOrderActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniNewWorkOrderActionPerformed
    {//GEN-HEADEREND:event_mniNewWorkOrderActionPerformed
        // create a new work order
        JOptionPane.showMessageDialog(this, "Method is not complete.");
        // set the current window to invisible
        //this.setVisible(false);
        // create the new work order window
        //new WorkOrder().setVisible(true);

    }//GEN-LAST:event_mniNewWorkOrderActionPerformed

    private void mniClearActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniClearActionPerformed
    {//GEN-HEADEREND:event_mniClearActionPerformed
        // clear the current work order fields
        JOptionPane.showMessageDialog(this, "Method is not complete.");
    }//GEN-LAST:event_mniClearActionPerformed

    private void mniOpenActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mniOpenActionPerformed
    {//GEN-HEADEREND:event_mniOpenActionPerformed
        // open an existing work order
        JOptionPane.showMessageDialog(this, "Method is not complete.");
    }//GEN-LAST:event_mniOpenActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoginActionPerformed
    {//GEN-HEADEREND:event_btnLoginActionPerformed
       // Get the entered username and password
    String username = txtUserID.getText();
    String password = txtPassword.getText();

    // Ensure employeeDB is initialized
    EmployeeDB employeeDB = new EmployeeDB();  

    // Authenticate Employee
    if (employeeDB.authenticateEmployee(username, password)) {
        System.out.println("Successful Login");
        JOptionPane.showMessageDialog(null, "Login Successful");
    } else {
        System.out.println("Failed Login");
        JOptionPane.showMessageDialog(null, "Login Failed! Invalid credentials.");
    }
       
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLogoutActionPerformed
    {//GEN-HEADEREND:event_btnLogoutActionPerformed
        // logs out the current employee
        JOptionPane.showMessageDialog(this, "Logout Complete.");
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnLoadMaterialListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnLoadMaterialListActionPerformed
    {//GEN-HEADEREND:event_btnLoadMaterialListActionPerformed
        // Loads material list from database.
        JOptionPane.showMessageDialog(this, "Method is not complete.");
    }//GEN-LAST:event_btnLoadMaterialListActionPerformed

    private void btnDisplayToolListActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDisplayToolListActionPerformed
    {//GEN-HEADEREND:event_btnDisplayToolListActionPerformed
        displayTool();
    }//GEN-LAST:event_btnDisplayToolListActionPerformed

    private void btnAddToolActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAddToolActionPerformed
    {//GEN-HEADEREND:event_btnAddToolActionPerformed
        addTool();
        displayTool();
    }//GEN-LAST:event_btnAddToolActionPerformed

    private void txtToolNameActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtToolNameActionPerformed
    {//GEN-HEADEREND:event_txtToolNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToolNameActionPerformed

    private void txtToolIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtToolIDActionPerformed
    {//GEN-HEADEREND:event_txtToolIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtToolIDActionPerformed

    private void btnDeleteToo1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDeleteToo1ActionPerformed
    {//GEN-HEADEREND:event_btnDeleteToo1ActionPerformed
        deleteTool();
        displayTool();
    }//GEN-LAST:event_btnDeleteToo1ActionPerformed

    private void txtUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
         Adding employee into DB
        
          EmployeeDB employeeDB = new EmployeeDB();

        Employee newEmployee = new Employee( "Irv", "Gotti", "Irv.Gotti@example.com", "607-777-7651",
                "2024-03-06", "Materials", "IMS", 20000.00, "Manager", "IGotti", 
                "Hello123"); // Ensure password is hashed before storing

        employeeDB.addEmployee(newEmployee);

        System.out.println("New Employee: " + newEmployee.getFirstName() + " " + newEmployee.getLastName() + " Password: " + newEmployee.getPasswordHash()); // Check if ID is captured
        
    //
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTool;
    private javax.swing.JButton btnDeleteToo1;
    private javax.swing.JButton btnDisplayToolList;
    private javax.swing.JButton btnLoadMaterialList;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblCompanyName;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblStreet1;
    private javax.swing.JLabel lblToolID;
    private javax.swing.JLabel lblToolName;
    private javax.swing.JLabel lblToolSerialNumber;
    private javax.swing.JLabel lblToolValue;
    private javax.swing.JLabel lblUserID;
    private javax.swing.JLabel lblWorkOrder;
    private javax.swing.JMenuBar mnbMain;
    private javax.swing.JMenuItem mniClear;
    private javax.swing.JMenuItem mniExit;
    private javax.swing.JMenuItem mniNewWorkOrder;
    private javax.swing.JMenuItem mniOpen;
    private javax.swing.JMenu mnuEdit;
    private javax.swing.JMenu mnuFile;
    private javax.swing.JTabbedPane mnuMain;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMaterials;
    private javax.swing.JPanel pnlTools;
    private javax.swing.JPanel pnlWorkOrder;
    private javax.swing.JScrollPane scrToolTable;
    private javax.swing.JTable tblToolTable;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtToolID;
    private javax.swing.JTextField txtToolName;
    private javax.swing.JTextField txtToolSerialNumber;
    private javax.swing.JTextField txtToolValue;
    private javax.swing.JTextField txtUserID;
    private javax.swing.JTextField txtWorkOrderNumber;
    // End of variables declaration//GEN-END:variables

    // deletes tools from the database
    private void deleteTool()
    {
        JOptionPane.showMessageDialog(this, "This method is not complete.");
    }    
    
    // add tools to the database
    private void addTool()
    {
        // get the tool information
        String toolName = txtToolName.getText();
        String toolSerialNumber = txtToolSerialNumber.getText();
        double toolValue = Double.parseDouble(txtToolValue.getText());

        // create the tool object
        Tool tool = new Tool(0, toolName, toolSerialNumber, toolValue);

        // add the tool object to the database
        WarehouseDB db = new WarehouseDB();

        try
        {
            db.add(tool);
            //JOptionPane.showMessageDialog(this, "Record was returned to the database.");
            // clear the form
            txtToolName.setText("");
            txtToolSerialNumber.setText("");
            txtToolValue.setText("");
            // put the curser back on the name field
            txtToolName.requestFocus();
        } catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Error. Database driver not found.", "Driver not found.", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "Database Error:" + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }

// display tools in the database
    private void displayTool()
    {
        // Loads tool list from database.
        //================================================
        // display records on a JTable
        //================================================
        // show the headings
        DefaultTableModel tblModel = new DefaultTableModel();
        tblToolTable.setModel(tblModel);

        String[] colTitles =
        {
            "ID", "Name", "Serial Number", "Value"
        };
        tblModel.setColumnIdentifiers(colTitles);

        // read the student records
        WarehouseDB db = new WarehouseDB();
        try
        {
            ArrayList<Tool> records = db.getAll();
            //DecimalFormat fmt2 = new DecimalFormat("0.0");
            for (int i = 0; i < records.size(); i++)
            {
                Tool tool = records.get(i);

                Object[] row =
                {
                    tool.getToolID(), tool.getToolName(), tool.getToolSerialNumber(), tool.getToolValue()
                };

                tblModel.addRow(row);
            }

        } catch (ClassNotFoundException ex)
        {
            JOptionPane.showMessageDialog(this, "Error. Database driver not found.", "Driver not found.", JOptionPane.ERROR_MESSAGE);
        } catch (SQLException ex)
        {
            JOptionPane.showMessageDialog(this, "Database Error:" + ex.getMessage(), "Database Error", JOptionPane.ERROR_MESSAGE);
        }

    }

}
